# Generated by Django 3.2.6 on 2022-12-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.FileField(max_length=255, upload_to='media/'),
        ),
    ]
