# Generated by Django 3.2.6 on 2022-12-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20221214_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(upload_to='media/products'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.FileField(upload_to='media/products'),
        ),
    ]
