# Generated by Django 3.2.6 on 2022-12-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20221027_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
