# Generated by Django 3.2.6 on 2022-12-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.FileField(blank=True, upload_to='media/categories'),
        ),
    ]
